#!/bin/bash
# This file is used for submmiting jobs to ODU wahab cluster
# It lists all files with .sh extension and submit to the cluster
# List all files with with .sh extensions;
files=($(ls *.sh | sort -u))
if [[ "${#files[@]}" -ne 0 ]]; then
	for file in "${files[@]}";do
		noSh=$(echo "${file}" | cut -d '.' -f 1); # Remove .sh from filename
		if [[ ! -d "${noSh}" ]]; then  
			sbatch "${file}"
		else
			echo "${noSh} folder already exist"
		fi
	done
else
	echo "No .sh files are present"
fi

exit;

